steps:
  # 1. Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-app'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/starful-repo/starful-web:$BUILD_ID',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/starful-repo/starful-web:latest',
      '.'
    ]

  # 2. 빌드된 이미지를 Artifact Registry에 푸시 (배포 전 반드시 필요)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-app'
    args: [
      'push', 
      'us-central1-docker.pkg.dev/$PROJECT_ID/starful-repo/starful-web:$BUILD_ID'
    ]
    waitFor: ['build-app']

  # 3. 푸시된 이미지를 사용하여 Cloud Run에 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-app'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'starful-biz'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/starful-repo/starful-web:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
    waitFor: ['push-app']

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/starful-repo/starful-web:$BUILD_ID'